---
# tasks file for php

    - name: Install PHP Package on Ubuntu
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'php']
      when: ansible_os_family == "Debian"

    - name: Sets Up PHP Info Page
      template:
        src: "info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"
      when: ansible_os_family == "Debian"

    - name: Installing PHP
      yum:
        name: 
          - php 
          - php-mysql 
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Copying your php file in the /var/www/html
      copy:
        src: info.php.j2
        dest: /var/www/html/index.php
      when: ansible_os_family == "RedHat"

    - name: Adding LoadModule php5_module        modules/libphp5.so to /etc/httpd/conf/httpd.conf
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        line: "LoadModule php5_module        modules/libphp5.so"
      when: ansible_os_family == "RedHat"
